### ISSUE TITLE
error when compile native_hooks.c

### ISSUE THREAD

**Issue by jzck-ty** [fuzzware-fuzzer/fuzzware-emulator#1]
When executing this command（./build_docker.sh）, I got following errors:
……
make: Entering directory '/home/user/fuzzware/emulator/harness/fuzzware_harness/native'
rm -rf *.o core_peripherals/*.o native_hooks.so timer.so interrupt_triggers.so util.so state_snapshotting.so native_tracing.so uc_snapshot.so core_peripherals/cortexm_nvic.so core_peripherals/cortexm_systick.so
clang -fpic -Wall -Werror -I/home/user/fuzzware/emulator/harness/fuzzware_harness/native//../../../unicorn/fuzzware-unicorn/include -g -O3   -c -o native_hooks.o native_hooks.c
native_hooks.c:184:34: error: use of undeclared identifier 'UC_HOOK_BLOCK_UNCONDITIONAL'
    res |= uc_hook_add(uc, &tmp, UC_HOOK_BLOCK_UNCONDITIONAL, hook_block_debug, NULL, 1, 0);
                                 ^
native_hooks.c:464:65: error: use of undeclared identifier 'UC_HOOK_BLOCK_UNCONDITIONAL'
    return uc_hook_add(uc, &hook_block_cond_py_handlers_handle, UC_HOOK_BLOCK_UNCONDITIONAL, hook_block_cond_py_handlers, user_data, 1, 0);
                                                                ^
native_hooks.c:815:5: error: implicit declaration of function 'uc_fuzzer_init_cov' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    uc_fuzzer_init_cov(uc, bitmap, MAP_SIZE);
    ^
native_hooks.c:1116:9: error: implicit declaration of function 'uc_fuzzer_reset_cov' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        uc_fuzzer_reset_cov(uc, 1);
        ^
4 errors generated.
make: *** [native_hooks.o] Error 1
<builtin>: recipe for target 'native_hooks.o' failed

I have searched all the project and found no file contains "UC_HOOK_BLOCK_UNCONDITIONAL" 、"uc_fuzzer_init_cov" or “uc_fuzzer_reset_cov ”. I want to know how to solve these problems, thanks!

I also tried to install locally,  above errors still exist.

**Comment by Scepticz** [comment]
Hi jzck-ty,

We have not encountered this error before. `UC_HOOK_BLOCK_UNCONDITIONAL` is used, for example, in [native_hooks.c](https://github.com/fuzzware-fuzzer/fuzzware-emulator/blob/c454cb95e96e1c0d1921f3b9c0464f18569318c1/harness/fuzzware_harness/native/native_hooks.c). 

The value should be declared in the unicorn submodule (in the `fuzzware` branch of https://github.com/fuzzware-fuzzer/unicorn): https://github.com/fuzzware-fuzzer/unicorn/blob/8cb665bf67b1f8fa04cc916b25d20732d1fbcc81/include/unicorn/unicorn.h

As this value is not declared, I suspect Unicorn not be to pulled/checked out in the correct commit. My first assumption would be that your installation/source code setup to not quite be configured as expected. Have you started the installation at the main fuzzware repo at https://github.com/fuzzware-fuzzer/fuzzware? There you can use `[update.sh](https://github.com/fuzzware-fuzzer/fuzzware/blob/main/update.sh)` to make sure all repositories are pulled correctly. 

There always is the chance of something else being wrong, or no longer working with a new compiler update. But before diving into that, I would suggest you to clone a fresh install of the fuzzware main repo and start installing from there:

```
git clone https://github.com/fuzzware-fuzzer/fuzzware
cd fuzzware
./build_docker.sh
```

Does this still yield the same error?

**Comment by jzck-ty** [comment]
Problems have been solved. The reason was that I used the wrong unicorn version.
Thanks very much！

**Comment by Scepticz** [comment]
Great. I am closing the issue, then. :-)

**Comment by JWH-96** [comment]
Hello, I met the same problem. You said it was the problem of the unicorn version. Isn't the unicorn used by fuzzware already included in the project? And the author of the project has modified it. How do I just change the correct unicorn version? Do I need another independent installation? Please give me some instructions on how to do it. Thanks. @jzck-ty
